
const base = "@favorites";

export default {
  ADD_FAVORITE_REQUEST: `${base}/ADD_FAVORITE_REQUEST`,
  ADD_FAVORITE_SUCCESS: `${base}/ADD_FAVORITE_SUCCESS`,
  REMOVE_FAVORITE_REQUEST: `${base}/REMOVE_FAVORITE_REQUEST`,
  REMOVE_FAVORITE_SUCCESS: `${base}/REMOVE_FAVORITE_SUCCESS`,
};